from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED
import xml.etree.ElementTree as ET


SRC = Path(r"C:/코딩/검색왕/output/genai-foundation-template/genai-foundation-template.pptx")
OUT = Path(r"C:/코딩/교육설계/생성형AI_기초활용역량_템플릿원본적용.pptx")

NS = {"a": "http://schemas.openxmlformats.org/drawingml/2006/main"}


REPLACEMENTS = {
    1: [
        "생성형 AI 기초활용역량",
        "목적을 분명히 하고",
        "질문하게 하고, 판단까지 가는",
        "4MAT 기반 실전 강의",
        "White / Warm Gray",
        "Navy",
        "Slate",
        "Charcoal",
        "이 과정의 기준",
        "AI 기능 자랑보다 목적 정의, 질문 설계, 판단, 실습, 구조화가 먼저 보이는 화면",
        "오늘 다룰 축",
        "철학 3개",
        "4MAT 흐름",
        "예쁜 집 / 의사 비유",
        "CRAFTO · 10-80-10 · 1-3-1 · 피드백 루프 · 로드맵",
        "직군별 장면 · 종합실습",
        "4 Hours / Workshop Deck",
    ],
    2: [
        "SYSTEM",
        "Generative AI Collaboration / Foundation Course",
        "학습자 특성과 운영 기준",
        "이 과정에서 반복해서 붙잡아야 할 전제",
        "02",
        "학습자 특성",
        "혼합형 직군",
        "영업 · R&D · 품질 · 기획이 함께 듣는다",
        "중고경력자",
        "기초 설명은 쉽게, 적용은 얕지 않게 가야 한다",
        "실무 압박",
        "이론보다 현업 연결이 더 중요하다",
        "운영 원칙",
        "도구보다 목적",
        "왜 쓰는지와 진짜 결과를 먼저 본다",
        "질문이 먼저",
        "AI가 먼저 인터뷰하게 만든다",
        "판단은 사람",
        "초안 이후 점검과 선택을 반드시 남긴다",
        "실습 기준",
        "한 장면을 끝까지",
        "직군별 장면 하나로 반복 적용한다",
        "작게 자주 실습",
        "중간 실습이 마지막 종합실습으로 이어진다",
        "도구는 이동수단",
        "좋은 툴보다 좋은 길 설계가 먼저다",
        "최종 산출물",
        "내 장면 + 내 질문 + 내 판단",
    ],
    3: [
        "PHILOSOPHY",
        "Generative AI Collaboration / Foundation Course",
        "03",
        "좋은 AI 활용은",
        "더 화려한 답을 받는 일이 아니라,",
        "더 나은 판단에 도달하는 일이다.",
        "메시지 운용 팁",
        "문장은 1개로",
        "핵심 문장 하나만 크게 남긴다",
        "장식보다 여백",
        "강의자가 말로 풀고 화면은 기억만 남긴다",
        "철학 슬라이드",
        "첫 장, 전환 장, 마무리 장에서 특히 강하게 작동한다",
    ],
    4: [
        "FLOW",
        "Generative AI Collaboration / Foundation Course",
        "4MAT / 과정 흐름",
        "질문 설계 중심 강의에 맞는 4단 흐름",
        "04",
        "1",
        "Why",
        "왜 AI를 써도 여전히 답답한가",
        "2",
        "What",
        "AI를 어떤 도구로 이해할 것인가",
        "3",
        "How",
        "어떻게 질문하고 구조화하고 점검할 것인가",
        "4",
        "If",
        "그래서 내 업무에 무엇을 적용할 것인가",
        "작은 실습을 자주 넣고, 마지막에는 자기 업무 장면 하나로 종합하면 4시간 흐름이 안정적입니다.",
    ],
    5: [
        "COMPARE",
        "Generative AI Collaboration / Foundation Course",
        "사례 비교 슬라이드",
        "비유와 사례를 좌우로 비교할 때 쓰는 기본형",
        "05",
        "사례 A  |  예쁜 집",
        "겉모습이 좋아 보여도",
        "구조와 동선이 나쁘면 오래 쓰기 어렵다.",
        "사례 B  |  좋은 AI 답변",
        "화려해 보여도",
        "목적과 판단 기준이 없으면 현업에 남지 않는다.",
        "보이는 결과",
        "지속되는 결과",
        "답은 빨리 나온다",
        "그럴듯해 보인다",
        "설명은 쉬워 보인다",
        "의미가 맞춰진다",
        "판단 기준이 남는다",
        "팀에 다시 쓰기 쉽다",
        "핵심 메시지: 보기 좋은 답보다, 다시 사용할 수 있는 사고 구조가 더 중요하다.",
    ],
    6: [
        "JUDGMENT",
        "Generative AI Collaboration / Foundation Course",
        "잘못된 접근 vs 올바른 접근",
        "의사 비유처럼 접근 방식의 차이를 선명하게 보여주는 화면",
        "06",
        "잘못된 접근",
        "보고서를 바로 써달라고 한다",
        "질문 없이 곧바로 답 생성",
        "목적 · 청자 · 제약이 빠진다",
        "올바른 접근",
        "목적 확인 -> 상황 파악 -> 질문 설계 -> 초안 생성 -> 판단과 수정",
        "바로 답 요청",
        "인터뷰 후 생성",
        "같은 말도 뜻이 다를 수 있음",
        "어긋난 답이 반복됨",
        "판단 기준이 남지 않음",
        "의미 정렬이 가능해짐",
        "다시 쓸 수 있는 질문 구조가 남음",
        "실무 적용이 쉬워짐",
    ],
    7: [
        "CANVAS",
        "Generative AI Collaboration / Foundation Course",
        "CRAFTO 6칸 그리드",
        "실습과 정리에 자연스럽게 쓰이는 워크숍형 슬라이드",
        "07",
        "Context",
        "지금 어떤 상황인가",
        "무엇을 하려는가",
        "Role",
        "AI는 어떤 역할을 해야 하는가",
        "예: 질문하는 파트너",
        "Audience",
        "누가 이 결과를 보는가",
        "상사 / 고객 / 타부서 / 팀원",
        "Format",
        "어떤 형태로 받으면 바로 쓸 수 있는가",
        "보고 / 브리프 / 비교표 / 질문리스트",
        "Tone",
        "어느 수준과 말투가 필요한가",
        "비전공자 / 경영진 / 실무자",
        "Option",
        "제약, 금지선, 선택 기준은 무엇인가",
        "추정 금지 / 근거 우선",
        "활용 팁: 각 칸은 1문장 또는 키워드 3개 이내로 제한하면 실습 집중도가 높습니다.",
    ],
    8: [
        "FRAME",
        "Generative AI Collaboration / Foundation Course",
        "철학 / 프레임 / 노하우",
        "3층 구조로 강의 메시지를 압축할 때 쓰는 도식",
        "08",
        "철학",
        "무엇을 기준으로 AI를 사용할 것인가",
        "프레임",
        "질문 설계 · 판단 기준 · 적용 절차",
        "노하우",
        "프롬프트 문장화 · 예시 비교 · 실습 팁",
    ],
    9: [
        "LAYOUT",
        "Generative AI Collaboration / Foundation Course",
        "10 - 80 - 10 가로 분할",
        "도입 - 핵심 내용 - 정리 메시지를 한 장에 넣는 구조",
        "09",
        "처음 10",
        "핵심 프레임 / 목적 / 기준",
        "중간 80",
        "질문, 정리, 비교, 초안",
        "마지막 10",
        "선택, 검증, 책임",
        "처음과 끝은 사람이 잡아야 한다.",
    ],
    10: [
        "STRUCTURE",
        "Generative AI Collaboration / Foundation Course",
        "1 - 3 - 1 퍼널 구조",
        "큰 질문 하나를 세 가지 기준으로 풀고 다시 하나의 판단으로 모으기",
        "10",
        "핵심 질문 1개",
        "기준 1",
        "목적이 분명한가",
        "기준 2",
        "질문이 구체적인가",
        "기준 3",
        "판단이 가능한가",
        "최종 판단 1개",
        "이 질문은 현업에서 다시 쓸 수 있는 구조인가",
    ],
    11: [
        "LOOP",
        "Generative AI Collaboration / Foundation Course",
        "피드백 루프 4분면",
        "입력-생성-검토-수정의 반복을 워크숍형으로 보여주는 도식",
        "11",
        "입력",
        "목적과 상황 정의",
        "생성",
        "초안과 옵션 만들기",
        "검토",
        "기준으로 평가하기",
        "수정",
        "질문과 답을 다듬기",
        "판단",
        "사람이 최종 선택",
    ],
    12: [
        "ROADMAP",
        "Generative AI Collaboration / Foundation Course",
        "출발지점 - 목표지점 - 이동수단",
        "길찾기 비유처럼 현재 상태와 이동 방식을 정리하는 슬라이드",
        "12",
        "출발지점",
        "지금은 질문이 막연한 상태",
        "이동수단",
        "프레임 · 예시 · 실습 · 피드백",
        "목표지점",
        "판단 가능한 질문 구조를 갖춘 상태",
        "내 업무에 다시 쓸 수 있는 상태",
    ],
    13: [
        "WORKSHOP",
        "Generative AI Collaboration / Foundation Course",
        "실습 안내 슬라이드",
        "설명보다 참여를 유도하는 카드형 안내",
        "13",
        "이번 실습의 목표",
        "모호한 요청을",
        "현업에서 쓸 수 있는 질문 구조로 바꿔본다.",
        "진행 순서",
        "상황 1개 고르기",
        "진짜 원하는 결과 찾기",
        "인터뷰형 요청문 만들기",
        "짝과 서로 피드백",
        "최종 문장 다듬기",
        "체크포인트",
        "목적이 분명한가",
        "누가 읽는가",
        "무엇을 놓치면 안 되는가",
        "산출물 형태",
        "CRAFTO 1개 + 판단 기준 3개 + 수정 포인트 1개",
    ],
    14: [
        "SYNTHESIS",
        "Generative AI Collaboration / Foundation Course",
        "마지막 종합실습 캔버스",
        "강의 전체를 한 화면에서 다시 조합하는 마무리형 슬라이드",
        "14",
        "문제와 목적",
        "해결하고 싶은 실제 상황",
        "진짜 원하는 결과",
        "누가 결과를 사용할 것인가",
        "질문 구조",
        "Context",
        "Role",
        "Audience",
        "결과 형식",
        "Format",
        "Tone",
        "Option",
        "판단과 수정",
        "좋은 답인지 어떻게 판단할 것인가",
        "무엇을 다시 물어보면 더 좋아지는가",
        "내가 직접 판단할 최종 항목",
    ],
}


def replace_slide_text(xml_bytes: bytes, replacements: list[str]) -> bytes:
    root = ET.fromstring(xml_bytes)
    nodes = root.findall(".//a:t", NS)
    if len(nodes) != len(replacements):
        raise ValueError(f"text node count mismatch: xml has {len(nodes)}, replacements has {len(replacements)}")
    for node, new_text in zip(nodes, replacements):
        node.text = new_text
    return ET.tostring(root, encoding="utf-8", xml_declaration=True)


def build() -> None:
    with ZipFile(SRC, "r") as zin, ZipFile(OUT, "w", ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename.startswith("ppt/slides/slide") and item.filename.endswith(".xml"):
                slide_no = int(item.filename.split("slide")[-1].split(".xml")[0])
                if slide_no in REPLACEMENTS:
                    data = replace_slide_text(data, REPLACEMENTS[slide_no])
            zout.writestr(item, data)


if __name__ == "__main__":
    build()
    print(OUT)
